In [ ]:
import pandas as pd

In [29]:
import ast
import pandas as pd
import json
import os
import matplotlib.pyplot as plt
import seaborn as sns

dir_path = '/workspaces/CUBES/exp/jack/paper/thermostat_experiment/SI/energy_check/results'
files = [f for f in os.listdir(dir_path) if f.endswith('.json')]

results_data = []
temperature_data = []

for file in files:
    with open(os.path.join(dir_path, file), 'r') as f:
        data = json.load(f)
        case_number = int(file.split('case_')[1].split('_')[0])
        zone_number = int(file.split('zone_')[1].split('_')[0])
        threshold = int(file.split('threshold_')[1].split('_')[0])
        pattern = str(file.split('pattern_')[1].split('_')[0])

        pattern_mapping = {"once": 1,
                           "twice": 2,
                           "thrice": 3}

        pattern = pattern_mapping.get(pattern)

        results_data.append({
            'case': case_number,
            'zone': zone_number,
            'threshold': threshold,
            'pattern': pattern,
            'mean_episode_emissions': data.get('eval/mean_episode_emissions'),
            'energy_gas': data.get('eval/energy_gas'),
            'energy_electricity': data.get('eval/energy_electricity'),
            'mean_episode_cost': data.get('eval/mean_episode_cost'),
            'mean_episode_gas_cost': data.get('eval/mean_episode_gas_cost'),
            'mean_episode_electricity_cost': data.get('eval/mean_episode_electricity_cost'),
            'mean_episode_electricity_surplus': data.get('eval/mean_episode_electricity_surplus'),
            'mean_episode_reward': data.get('eval/mean_episode_reward'),
            'mean_episode_emissions_reward': data.get('eval/mean_episode_emissions_reward'),
            'mean_episode_comfort_reward': data.get('eval/mean_episode_comfort_reward'),
            'mean_episode_air_quality_reward': data.get('eval/mean_episode_air_quality_reward'),
            'mean_episode_ndt_t_violations': json.dumps(data.get('eval/mean_episode_ndt_t_violations')),
            'mean_episode_ndt_aq_violations': json.dumps(data.get('eval/mean_episode_ndt_aq_violations')),
            'mean_episode_heating_degree_days': json.dumps(data.get('eval/mean_episode_heating_degree_days')),
            'mean_episode_heating_service_degree_days': json.dumps(data.get('eval/mean_episode_heating_service_degree_days')),
            'mean_episode_max_heating_service_degree_days': json.dumps(data.get('eval/mean_episode_max_heating_service_degree_days')),
            'mean_episode_heating_beyond_comfort_degree_days': json.dumps(data.get('eval/mean_episode_heating_beyond_comfort_degree_days')),
            'mean_episode_violation_degree_days': data.get('eval/mean_episode_violation_degree_days'),
            'mean_episode_violation_ppm_days': json.dumps(data.get('eval/mean_episode_violation_ppm_days')),
            'mean_episode_cost_reward': data.get('eval/mean_episode_cost_reward')
        })

        temperature_data.append({
            'case': case_number,
            'zone': zone_number,
            'threshold': threshold,
            'pattern': pattern,
            'air_temperature_distribution': json.dumps(data.get('eval/air_temperature_distribution')),
            'opr_temperature_distribution': json.dumps(data.get('eval/opr_temperature_distribution'))
        })

results_df = pd.DataFrame(results_data).sort_values(by='case')
temperature_df = pd.DataFrame(temperature_data)




# Convert the 'air_temperature_distribution' column from string to dictionary
temperature_df['air_temperature_distribution'] = (
    temperature_df['air_temperature_distribution']
    .apply(ast.literal_eval)
)

# Convert 'opr_temperature_distribution' similarly if it's stored as a string
temperature_df['opr_temperature_distribution'] = (
    temperature_df['opr_temperature_distribution']
    .apply(ast.literal_eval)
)

In [30]:
results_df["energy_electricity"] = (results_df["energy_electricity"]/(1000*60))
results_df["mean_episode_cost"] = (results_df["mean_episode_cost"]/(100))
results_df["mean_episode_emissions"] = (results_df["mean_episode_emissions"]/(1000))

summary_df = results_df[["case", "zone", 'mean_episode_emissions', 'energy_gas', 'energy_electricity', 'mean_episode_cost']]
summary_df = summary_df.reset_index(drop="True")

In [33]:
results_df

,case,zone,threshold,pattern,mean_episode_emissions,energy_gas,energy_electricity,mean_episode_cost,mean_episode_gas_cost,mean_episode_electricity_cost,...,mean_episode_air_quality_reward,mean_episode_ndt_t_violations,mean_episode_ndt_aq_violations,mean_episode_heating_degree_days,mean_episode_heating_service_degree_days,mean_episode_max_heating_service_degree_days,mean_episode_heating_beyond_comfort_degree_days,mean_episode_violation_degree_days,mean_episode_violation_ppm_days,mean_episode_cost_reward
8,0,0,30,2,2.416187,12906.981635,0.000000,728.517053,72851.705330,0.000000,...,-0.415977,"{""hall_downstairs"": 116.0, ""front_room"": 39.0,...","{""hall_downstairs"": 24959.0, ""front_room"": 599...","{""hall_downstairs"": 880.4105429531917, ""front_...","{""hall_downstairs"": 929.2743634197377, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 7.465123164029602, ""front_...",0.178227,"{""hall_downstairs"": 39265.0806035827, ""front_r...",-0.113394
4,1,0,30,2,2.343963,12521.171992,0.000000,707.587776,70758.777637,0.000000,...,-0.447244,"{""hall_downstairs"": 80.0, ""front_room"": 45.0, ...","{""hall_downstairs"": 25757.0, ""front_room"": 647...","{""hall_downstairs"": 875.3074605166779, ""front_...","{""hall_downstairs"": 929.2630577506437, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 6.784382327277471, ""front_...",0.191615,"{""hall_downstairs"": 41475.83492045458, ""front_...",-0.110137
3,2,0,30,2,2.234248,11935.087676,0.000000,675.470917,67547.091668,0.000000,...,-0.463860,"{""hall_downstairs"": 61.0, ""front_room"": 32.0, ...","{""hall_downstairs"": 26103.0, ""front_room"": 680...","{""hall_downstairs"": 871.5146587967172, ""front_...","{""hall_downstairs"": 929.2551336267757, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 6.553753612453079, ""front_...",0.198006,"{""hall_downstairs"": 42631.006802839824, ""front...",-0.105138
7,3,0,30,2,1.532443,7651.811670,656.737200,507.134970,43470.197147,14456.246925,...,-0.029179,"{""hall_downstairs"": 7627.0, ""front_room"": 5540...","{""hall_downstairs"": 4795.0, ""front_room"": 749....","{""hall_downstairs"": 1046.9826177281284, ""front...","{""hall_downstairs"": 918.5475435718471, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 163.6332984843014, ""front_...",6.440708,"{""hall_downstairs"": 2217.65120372841, ""front_r...",-0.078936
1,4,0,30,2,0.976670,4682.939177,656.737200,340.016088,26758.308960,14456.246925,...,-0.038811,"{""hall_downstairs"": 6754.0, ""front_room"": 4095...","{""hall_downstairs"": 5183.0, ""front_room"": 1004...","{""hall_downstairs"": 1062.4596549643488, ""front...","{""hall_downstairs"": 905.4293492848541, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 192.381257959571, ""front_r...",11.987344,"{""hall_downstairs"": 2593.3034569329866, ""front...",-0.052924
9,5,0,30,2,0.934192,0.000000,5503.447694,734.641732,0.000000,151453.213330,...,-0.415710,"{""hall_downstairs"": 47.0, ""front_room"": 28.0, ...","{""hall_downstairs"": 24949.0, ""front_room"": 599...","{""hall_downstairs"": 721.9066801816008, ""front_...","{""hall_downstairs"": 929.3283673249337, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 2.8706235227738097, ""front...",0.150385,"{""hall_downstairs"": 39175.118265749814, ""front...",-0.114347
11,6,0,30,2,0.911949,0.000000,5355.483430,716.151283,0.000000,147733.738400,...,-0.446949,"{""hall_downstairs"": 45.0, ""front_room"": 34.0, ...","{""hall_downstairs"": 25749.0, ""front_room"": 646...","{""hall_downstairs"": 735.3497115962864, ""front_...","{""hall_downstairs"": 929.3260636780225, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 2.7749719063772664, ""front...",0.155559,"{""hall_downstairs"": 41380.32620129534, ""front_...",-0.111469
2,7,0,30,2,0.871135,0.000000,5098.263701,683.468900,0.000000,141154.946647,...,-0.463565,"{""hall_downstairs"": 51.0, ""front_room"": 30.0, ...","{""hall_downstairs"": 26086.0, ""front_room"": 680...","{""hall_downstairs"": 723.2718667068568, ""front_...","{""hall_downstairs"": 929.3148667458548, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 3.428967591829434, ""front_...",0.166318,"{""hall_downstairs"": 42536.57576339212, ""front_...",-0.106382
10,8,0,30,2,0.661439,0.000000,3925.231692,511.653457,0.000000,105887.291130,...,-0.029076,"{""hall_downstairs"": 4908.0, ""front_room"": 5408...","{""hall_downstairs"": 4768.0, ""front_room"": 748....","{""hall_downstairs"": 1096.8529034094524, ""front...","{""hall_downstairs"": 923.505846938126, ""front_r...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 209.24455503902894, ""front...",5.483495,"{""hall_downstairs"": 2189.2124111903013, ""front...",-0.079639
0,9,0,30,2,0.453583,0.000000,2709.187582,348.111965,0.000000,71840.995164,...,-0.038595,"{""hall_downstairs"": 4278.0, ""front_room"": 2282...","{""hall_downstairs"": 5145.0, ""front_room"": 1002...","{""hall_downstairs"": 1126.3603338729852, ""front...","{""hall_downstairs"": 913.3816958401663, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 248.93556178721158, ""front...",7.284659,"{""hall_downstairs"": 2554.998758671009, ""front_...",-0.054184
6,10,0,30,2,0.730388,0.000000,5488.943939,569.452329,0.000000,116943.820940,...,-0.415727,"{""hall_downstairs"": 45.0, ""front_room"": 30.0, ...","{""hall_downstairs"": 24948.0, ""front_room"": 599...","{""hall_downstairs"": 855.9192500235637, ""front_...","{""hall_downstairs"": 929.3297745129631, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 54.231408224120905, ""front...",0.149389,"{""hall_downstairs"": 39176.22451645539, ""front_...",-0.088636
13,11,0,30,2,0.703309,0.000000,5284.197590,547.496929,0.000000,112417.284720,...,-0.446978,"{""hall_downstairs"": 46.0, ""front_room"": 33.0, ...","{""hall_downstairs"": 25748.0, ""front_room"": 646...","{""hall_downstairs"": 839.3346421589664, ""front_...","{""hall_downstairs"": 929.3107255953016, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 54.97394643275765, ""front_...",0.166080,"{""hall_downstairs"": 41383.10440797659, ""front_...",-0.085218
12,12,0,30,2,0.676285,0.000000,5095.171476,525.772428,0.000000,107950.782265,...,-0.463574,"{""hall_downstairs"": 51.0, ""front_room"": 29.0, ...","{""hall_downstairs"": 26088.0, ""front_room"": 680...","{""hall_downstairs"": 859.4075741043354, ""front_...","{""hall_downstairs"": 929.3159484456811, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 57.68459318450749, ""front_...",0.164206,"{""hall_downstairs"": 42536.89047912702, ""front_...",-0.081837
5,13,0,30,2,0.440006,0.000000,3929.834001,344.216026,0.000000,70063.391265,...,-0.029081,"{""hall_downstairs"": 4936.0, ""front_room"": 5412...","{""hall_downstairs"": 4768.0, ""front_room"": 748....","{""hall_downstairs"": 910.346499988274, ""front_r...","{""hall_downstairs"": 923.4984033436284, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 101.33112493803758, ""front...",5.495354,"{""hall_downstairs"": 2189.535354104168, ""front_...",-0.053577
14,14,0,30,2,0.254282,0.000000,2720.921595,199.090820,0.000000,39893.122418,...,-0.038596,"{""hall_downstairs"": 4130.0, ""front_room"": 1811...","{""hall_downstairs"": 5146.0, ""front_room"": 999....","{""hall_downstairs"": 928.3688934344393, ""front_...","{""hall_downstairs"": 914.5841869750998, ""front_...","{""hall_downstairs"": 929.5072858796318, ""front_...","{""hall_downstairs"": 125.15485517113639, ""front...",6.270560,"{""hall_downstairs"": 2555.420930896146, ""front_...",-0.030989

In [54]:
summary_df = results_df[["case", "zone", 'mean_episode_emissions', 'energy_gas', 'energy_electricity', 'mean_episode_cost']]
summary_df = summary_df.reset_index(drop="True")

In [55]:
summary_df

,case,zone,mean_episode_emissions,energy_gas,energy_electricity,mean_episode_cost
0,0,0,2.416187,12906.981635,0.000000,728.517053
1,1,0,2.343963,12521.171992,0.000000,707.587776
2,2,0,2.234248,11935.087676,0.000000,675.470917
3,3,0,1.532443,7651.811670,656.737200,507.134970
4,4,0,0.976670,4682.939177,656.737200,340.016088
5,5,0,0.934192,0.000000,5503.447694,734.641732
6,6,0,0.911949,0.000000,5355.483430,716.151283
7,7,0,0.871135,0.000000,5098.263701,683.468900
8,8,0,0.661439,0.000000,3925.231692,511.653457
9,9,0,0.453583,0.000000,2709.187582,348.111965
10,10,0,0.730388,0.000000,5488.943939,569.452329
11,11,0,0.703309,0.000000,5284.197590,547.496929
12,12,0,0.676285,0.000000,5095.171476,525.772428
13,13,0,0.440006,0.000000,3929.834001,344.216026
14,14,0,0.254282,0.000000,2720.921595,199.090820

In [61]:
summary_df.loc[:5, "energy_demand"] = summary_df.loc[:4, "energy_gas"]/ (8.1*5.4*2)
summary_df.loc[5:, "energy_demand"] = summary_df.loc[4:, "energy_electricity"]/ (8.1*5.4*2)

In [63]:
summary_df.iloc[0:5,:]

,case,zone,mean_episode_emissions,energy_gas,energy_electricity,mean_episode_cost,energy_demand
0,0,0,2.416187,12906.981635,0.0000,728.517053,147.542085
1,1,0,2.343963,12521.171992,0.0000,707.587776,143.131824
2,2,0,2.234248,11935.087676,0.0000,675.470917,136.432187
3,3,0,1.532443,7651.811670,656.7372,507.134970,87.469269
4,4,0,0.976670,4682.939177,656.7372,340.016088,53.531541