In [33]:
import numpy as np
import ast
import pandas as pd
import json
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:


dir_path = '/workspaces/CUBES/exp/jack/paper/thermostat_experiment/output/results_thermostat_test'
files = [f for f in os.listdir(dir_path) if f.endswith('.json')]

results_data = []
temperature_data = []

for file in files:
    with open(os.path.join(dir_path, file), 'r') as f:
        data = json.load(f)
        case_number = int(file.split('case_')[1].split('_')[0])
        zone_number = int(file.split('zone_')[1].split('_')[0])
        threshold = int(file.split('threshold_')[1].split('_')[0])
        pattern = str(file.split('pattern_')[1].split('_')[0])

        pattern_mapping = {"once": 1,
                           "twice": 2,
                           "thrice": 3}

        pattern = pattern_mapping.get(pattern)

        results_data.append({
            'case': case_number,
            'zone': zone_number,
            'threshold': threshold,
            'pattern': pattern,
            'mean_episode_reward': data.get('eval/mean_episode_reward'),
            'mean_episode_emissions_reward': data.get('eval/mean_episode_emissions_reward'),
            'mean_episode_comfort_reward': data.get('eval/mean_episode_comfort_reward'),
            'mean_episode_air_quality_reward': data.get('eval/mean_episode_air_quality_reward'),
            'mean_episode_emissions': data.get('eval/mean_episode_emissions'),
            'mean_episode_ndt_t_violations': json.dumps(data.get('eval/mean_episode_ndt_t_violations')),
            'mean_episode_ndt_aq_violations': json.dumps(data.get('eval/mean_episode_ndt_aq_violations')),
            'mean_episode_heating_degree_days': json.dumps(data.get('eval/mean_episode_heating_degree_days')),
            'mean_episode_heating_service_degree_days': json.dumps(data.get('eval/mean_episode_heating_service_degree_days')),
            'mean_episode_max_heating_service_degree_days': json.dumps(data.get('eval/mean_episode_max_heating_service_degree_days')),
            'mean_episode_heating_beyond_comfort_degree_days': json.dumps(data.get('eval/mean_episode_heating_beyond_comfort_degree_days')),
            'mean_episode_violation_degree_days': data.get('eval/mean_episode_violation_degree_days'),
            'mean_episode_violation_ppm_days': json.dumps(data.get('eval/mean_episode_violation_ppm_days')),
            'mean_episode_cost': data.get('eval/mean_episode_cost'),
            'mean_episode_gas_cost': data.get('eval/mean_episode_gas_cost'),
            'mean_episode_electricity_cost': data.get('eval/mean_episode_electricity_cost'),
            'mean_episode_electricity_surplus': data.get('eval/mean_episode_electricity_surplus'),
            'mean_episode_cost_reward': data.get('eval/mean_episode_cost_reward')
        })

        temperature_data.append({
            'case': case_number,
            'zone': zone_number,
            'threshold': threshold,
            'pattern': pattern,
            'air_temperature_distribution': json.dumps(data.get('eval/air_temperature_distribution')),
            'opr_temperature_distribution': json.dumps(data.get('eval/opr_temperature_distribution'))
        })

results_df = pd.DataFrame(results_data).sort_values(by='case')
temperature_df = pd.DataFrame(temperature_data)




# Convert the 'air_temperature_distribution' column from string to dictionary
temperature_df['air_temperature_distribution'] = (
    temperature_df['air_temperature_distribution']
    .apply(ast.literal_eval)
)

# Convert 'opr_temperature_distribution' similarly if it's stored as a string
temperature_df['opr_temperature_distribution'] = (
    temperature_df['opr_temperature_distribution']
    .apply(ast.literal_eval)
)

In [38]:
results_df = results_df.sort_values(by=["case",'zone'])
zone0 = results_df[results_df["zone"] == 0]
zone0 = zone0[["case", "mean_episode_emissions", "mean_episode_cost"]]
zone0 = zone0.reset_index(drop=True)
zone0["relative_emissions"] = zone0["mean_episode_emissions"]/zone0["mean_episode_emissions"].iloc[0]

zone0["energy"] = np.where(
    zone0["case"] < 5,
    zone0["mean_episode_cost"] / 5,  # If case < 0
    zone0["mean_episode_cost"] / 24.50  # Else
)

zone0["mean_episode_cost"] = zone0["mean_episode_cost"]/100

zone0["annual_demand"] = zone0["energy"]/ ((5.4*8.1)*2)

In [39]:
zone0

,case,mean_episode_emissions,mean_episode_cost,relative_emissions,energy,annual_demand
0,0,2416.186769,728.517053,1.000000,14570.341066,166.556254
1,1,2343.963209,707.587776,0.970108,14151.755527,161.771325
2,2,2234.248234,675.470917,0.924700,13509.418334,154.428650
3,3,1532.442536,507.134970,0.634240,10142.699406,115.943066
4,4,976.669650,340.016088,0.404219,6800.321769,77.735731
5,5,934.192321,734.641732,0.386639,2998.537680,34.276837
6,6,911.948641,716.151283,0.377433,2923.066463,33.414111
7,7,871.135188,683.468900,0.360541,2789.668978,31.889220
8,8,661.439342,511.653457,0.273753,2088.381457,23.872673
9,9,453.583108,348.111965,0.187727,1420.865165,16.242172
10,10,730.387766,569.452329,0.302289,2324.295222,26.569447
11,11,703.308911,547.496929,0.291082,2234.681343,25.545054
12,12,676.284506,525.772428,0.279897,2146.009912,24.531435
13,13,440.006176,344.216026,0.182108,1404.963371,16.060395
14,14,254.281886,199.090820,0.105241,812.615593,9.289159

In [43]:
results_df = results_df.sort_values(by=["case",'zone'])
zone9 = results_df[results_df["zone"] == 9]
zone9 = zone9[["case", "mean_episode_emissions", "mean_episode_cost"]]
zone9 = zone9.reset_index(drop=True)
zone9["relative_emissions"] = zone9["mean_episode_emissions"]/zone9["mean_episode_emissions"].iloc[0]

zone9["energy"] = np.where(
    zone9["case"] < 5,
    zone9["mean_episode_cost"] / 5,  # If case < 0
    zone9["mean_episode_cost"] / 24.50  # Else
)

zone9["mean_episode_cost"] = zone9["mean_episode_cost"]/100

zone9["annual_demand"] = zone9["energy"]/ ((5.4*8.1)*2)

In [44]:
zone9

,case,mean_episode_emissions,mean_episode_cost,relative_emissions,energy,annual_demand
0,0,1856.786580,568.686838,1.000000,11373.736762,130.015281
1,1,1799.889500,551.734350,0.969357,11034.687006,126.139541
2,2,1713.585719,525.825867,0.922877,10516.517331,120.216247
3,3,1106.585944,382.469460,0.595968,7649.389208,87.441578
4,4,676.570663,251.559564,0.364377,5031.191277,57.512475
5,5,724.242008,555.625876,0.390051,2267.860718,25.924334
6,6,706.808949,541.398544,0.380662,2209.789978,25.260516
7,7,674.595194,516.052433,0.363313,2106.336462,24.077920
8,8,506.498437,380.941360,0.272782,1554.862694,17.773922
9,9,346.005710,255.901828,0.186347,1044.497257,11.939841
10,10,562.106350,428.554531,0.302731,1749.202167,19.995452
11,11,539.331374,410.174258,0.290465,1674.180644,19.137867
12,12,517.946202,393.235238,0.278948,1605.041789,18.347528
13,13,314.827077,238.064852,0.169555,971.693274,11.107605
14,14,170.904248,125.270719,0.092043,511.309059,5.844868

In [47]:
comp = (zone0["mean_episode_cost"] - zone9["mean_episode_cost"])/zone0["mean_episode_cost"]

In [48]:
comp

0     0.219391
1     0.220260
2     0.221542
3     0.245823
4     0.260154
5     0.243678
6     0.244017
7     0.244951
8     0.255470
9     0.264886
10    0.247427
11    0.250819
12    0.252081
13    0.308385
14    0.370786
Name: mean_episode_cost, dtype: float64